version: '3.9'

services:
  django:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/app
    container_name: bancas_container
    image: bancas:1.0
    ports:
      - 8000:8000