# Generated by Django 4.2.1 on 2023-05-27 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('loan_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
                ('finance_type', models.CharField(choices=[('credit', 'Credit'), ('debt', 'Debt')], default='credit', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField(max_length=14)),
                ('address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField(max_length=14)),
                ('id_card', models.ImageField(upload_to='ids/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
