# Generated by Django 4.2.1 on 2023-05-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_loanapplication_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='ids/'),
        ),
    ]
