# Generated by Django 4.2.1 on 2023-05-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_loanapplication_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
