# Generated by Django 4.2.1 on 2023-06-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_loanapplication_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
