# Generated by Django 4.2.1 on 2023-06-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_loanapplication_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=34, max_digits=15),
            preserve_default=False,
        ),
    ]
