# Generated by Django 4.2.1 on 2023-06-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_loanstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
