# Generated by Django 4.2.1 on 2023-06-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_loanapplication_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='LoanStatus',
        ),
    ]
