# Generated by Django 4.2.1 on 2023-05-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_alter_loan_interest_rate_alter_loan_loan_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsaccount',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
