# Generated by Django 4.2.1 on 2023-05-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0006_profile_email_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
