# Generated by Django 4.2.1 on 2023-05-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0010_transaction_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
    ]
